In [63]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [64]:
df=pd.read_csv("Bike Prices.csv")
df.head()

,Brand,Model,Selling_Price,Year,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
0,TVS,TVS XL 100,30000,2017,Individual,1st owner,8000,30490.0
1,Bajaj,Bajaj ct 100,18000,2017,Individual,1st owner,35000,32000.0
2,Yo,Yo Style,20000,2011,Individual,1st owner,10000,37675.0
3,Bajaj,Bajaj Discover 100,25000,2010,Individual,1st owner,43000,42859.0
4,Bajaj,Bajaj Discover 100,24999,2012,Individual,2nd owner,35000,42859.0

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              1061 non-null   str
 1   Model              1061 non-null   str
 2   Selling_Price      1061 non-null   int64
 3   Year               1061 non-null   int64
 4   Seller_Type        1061 non-null   str
 5   Owner              1061 non-null   str
 6   KM_Driven          1061 non-null   int64
 7   Ex_Showroom_Price  626 non-null    float64
dtypes: float64(1), int64(3), str(4)
memory usage: 66.4 KB

In [66]:
df.isnull().sum()

Brand                  0
Model                  0
Selling_Price          0
Year                   0
Seller_Type            0
Owner                  0
KM_Driven              0
Ex_Showroom_Price    435
dtype: int64

In [67]:
df[df['Ex_Showroom_Price'].isnull()]

,Brand,Model,Selling_Price,Year,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
626,Royal,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
627,Honda,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
628,Yamaha,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN
629,Royal,Royal Enfield Bullet 350 [2007-2011],180000,2008,Individual,2nd owner,39000,NaN
630,Hero,Hero Honda CBZ extreme,30000,2010,Individual,1st owner,32000,NaN
...,...,...,...,...,...,...,...,...
1056,Royal,Royal Enfield Electra 5 S,90000,2012,Individual,1st owner,40000,NaN
1057,Hero,Hero Honda Hunk,20000,2010,Individual,1st owner,17000,NaN
1058,Bajaj,Bajaj Pulsar 220 DTS-i,60000,2014,Individual,1st owner,16000,NaN
1059,Hero,Hero Honda CBZ extreme,40000,2009,Individual,1st owner,50000,NaN
1060,Hero,Hero Honda CBZ extreme,35000,2012,Individual,1st owner,60000,NaN

In [68]:
df['Ex_Showroom_Price']=df['Ex_Showroom_Price'].fillna(df['Ex_Showroom_Price'].median())

In [69]:
num_features=[col for col in df.columns if df[col].dtype!='str']
cat_features=[col for col in df.columns if df[col].dtype=='str']
print("num of numeric features :",len(num_features))
print("num of catgorical features :",len(cat_features))

num of numeric features : 4
num of catgorical features : 4

In [70]:
num_features = df.select_dtypes(include=['int64','float64']).columns
cat_features = df.select_dtypes(include=['object','category']).columns

print('Num of Numerical Features:', len(num_features))
print('Num of Categorical Features:', len(cat_features))

Num of Numerical Features: 4
Num of Categorical Features: 4

In [71]:
Descreate_features=[col for col in num_features if len(df[col].unique())<=25]
continues_features=[col for col in num_features if len(df[col].unique())>25]
print("num of Descreate features :",len(Descreate_features))
print("num of Continues features :",len(continues_features))

num of Descreate features : 0
num of Continues features : 4

In [72]:
Discreate_featuers=[col for col in num_features if len(df[col].unique())<=25]
continues_featuers=[col for col in num_features if len(df[col].unique())>25]
print("Num of Discreate feature :",len(Discreate_featuers))
print("Num of continues feature :",len(continues_featuers))

Num of Discreate feature : 0
Num of continues feature : 4

In [85]:
df['Model'].value_counts()

Model
Bajaj Pulsar 150             41
Royal Enfield Classic 350    27
Honda Activa [2000-2015]     23
Honda CB Hornet 160R         22
Bajaj Pulsar 180             20
                             ..
Honda Grazia                  1
TVS Apache [2006]             1
Suzuki SlingShot              1
Yamaha Gladiator              1
TVS Max DLX                   1
Name: count, Length: 279, dtype: int64

In [89]:
df['Brand'].value_counts()

Brand
Bajaj       260
Hero        232
Honda       204
Royal       109
Yamaha      102
TVS          69
Suzuki       30
KTM          24
Mahindra      6
Vespa         4
Kawasaki      4
Activa        3
UM            3
Jawa          3
Harley        2
Aprilia       2
Yo            1
Benelli       1
Hyosung       1
BMW           1
Name: count, dtype: int64

In [92]:
df[df['Brand']=='Royal'].describe()

       Selling_Price      KM_Driven  Ex_Showroom_Price
count     109.000000     109.000000         109.000000
mean   128549.541284   20732.935780      106756.371560
std     42971.124292   34131.866124       46616.285947
min     59000.000000     350.000000       72752.500000
25%    100000.000000    6330.000000       72752.500000
50%    123000.000000   15000.000000       72752.500000
75%    150000.000000   25000.000000      148114.000000
max    299000.000000  345000.000000      208902.000000

In [94]:
df[df['Brand'].str.contains('Bajaj', case=False, na=False)]

,Brand,Model,Selling_Price,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
1,Bajaj,Bajaj ct 100,18000,Individual,1st owner,35000,32000.0
3,Bajaj,Bajaj Discover 100,25000,Individual,1st owner,43000,42859.0
4,Bajaj,Bajaj Discover 100,24999,Individual,2nd owner,35000,42859.0
5,Bajaj,Bajaj Discover 100,20000,Individual,1st owner,85000,42859.0
6,Bajaj,Bajaj Discover 100,30000,Individual,1st owner,45000,42859.0
...,...,...,...,...,...,...,...
1042,Bajaj,Bajaj Pulsar 150,70000,Individual,1st owner,24000,72752.5
1048,Bajaj,Bajaj Pulsar 150 [2001-2011],30000,Individual,1st owner,19500,72752.5
1050,Bajaj,Bajaj Pulsar 150,40000,Individual,2nd owner,65000,72752.5
1054,Bajaj,Bajaj Boxer,15000,Individual,1st owner,18000,72752.5
1058,Bajaj,Bajaj Pulsar 220 DTS-i,60000,Individual,1st owner,16000,72752.5

In [88]:
df.head(100)

,Brand,Model,Selling_Price,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
0,TVS,TVS XL 100,30000,Individual,1st owner,8000,30490.0
1,Bajaj,Bajaj ct 100,18000,Individual,1st owner,35000,32000.0
2,Yo,Yo Style,20000,Individual,1st owner,10000,37675.0
3,Bajaj,Bajaj Discover 100,25000,Individual,1st owner,43000,42859.0
4,Bajaj,Bajaj Discover 100,24999,Individual,2nd owner,35000,42859.0
...,...,...,...,...,...,...,...
95,Hero,Hero Splendor iSmart,40000,Individual,1st owner,19055,52271.0
96,Hero,Hero Splendor iSmart,40000,Individual,1st owner,10000,52271.0
97,TVS,TVS Scooty Zest 110,28000,Individual,1st owner,32800,52372.0
98,Bajaj,Bajaj Discover 110,15000,Individual,1st owner,70000,52710.0
99,Hero,Hero Maestro Edge,25000,Individual,1st owner,55000,52790.0

In [74]:
df=df.drop('Year',axis=1)

In [75]:
df=df.dropna()
X=df.drop('Selling_Price',axis=1)
y=df['Selling_Price']

In [76]:
df.columns

Index(['Brand', 'Model', 'Selling_Price', 'Seller_Type', 'Owner', 'KM_Driven',
       'Ex_Showroom_Price'],
      dtype='str')

In [77]:
X.columns

Index(['Brand', 'Model', 'Seller_Type', 'Owner', 'KM_Driven',
       'Ex_Showroom_Price'],
      dtype='str')

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [79]:
X_train.shape,X_test.shape

((795, 6), (266, 6))

In [80]:
print(type(X_train))

<class 'pandas.DataFrame'>

In [81]:
cat_features=X.select_dtypes(include='object').columns
num_features=X.select_dtypes(exclude='object').columns

In [82]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
numeric_transformation=StandardScaler()
oh_transformation=OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False)
preprocesser=ColumnTransformer(
    transformers=[
        ("OneHotEncoder",oh_transformation,cat_features),
        ("StandardScaler",numeric_transformation,num_features)
    ]
)

In [84]:
import pickle
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor

pipeline = Pipeline(steps=[
    ("preprocessor", preprocesser),
    ("model", XGBRegressor())
])

pipeline.fit(X_train, y_train)

pickle.dump(pipeline, open("model.pkl", "wb"))

In [37]:
X_train=preprocesser.fit_transform(X_train)
X_test=preprocesser.transform(X_test)

In [38]:
X1=pd.DataFrame(X_train)
X1

,0,1,2,3,4,5,6,7,8,9,...,256,257,258,259,260,261,262,263,264,265
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.326363,0.026567
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.136537,0.563151
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.519222,-0.150902
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.070544,-0.431115
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.050253,-0.127085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.050253,-0.127085
791,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.550701,0.069091
792,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.622763,-0.435839
793,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.053288,-0.150902
794,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.188308,-0.150902

In [39]:
# plt.figure(figsize=(15,5))
# corr=X1.corr()
# sns.heatmap(corr)

In [40]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor,RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [41]:
models={
    "Linear":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "Decision Tree":DecisionTreeRegressor(),
    "KNN":KNeighborsRegressor(),
    "Gradient Boost":GradientBoostingRegressor(),
    "AdaBoost":AdaBoostRegressor(),
    "Random Forest":RandomForestRegressor(),
    "XGB":XGBRegressor()
}

In [42]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    # y_train_pred=(model.predict_proba(X_train)[:,1]>=0.5).astype(int)
    # y_test_pred=(model.predict_proba(X_test)[:,1]>=0.5).astype(int)
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    model_train_mae=mean_absolute_error(y_train,y_train_pred)
    model_train_mean_squared_error=mean_squared_error(y_train,y_train_pred)
    model_train_r2_score=r2_score(y_train,y_train_pred)
  
    
    
    model_test_mae=mean_absolute_error(y_test,y_test_pred)
    model_test_mean_squared_error=mean_squared_error(y_test,y_test_pred)
    model_test_r2_score=r2_score(y_test,y_test_pred)

    
    print(list(models.keys())[i])
    
    print('Model performnace for traning set')
    print("- mae:{:.4f}".format(model_train_mae))
    print("- mse:{:.4f}".format(model_train_mean_squared_error))
    print("- r2_score:{:.4f}".format(model_train_r2_score))

    
    print("------------------------------------- ")
    
    print('Model performnace for testing set')
    
    print("- mae:{:.4f}".format(model_test_mae))
    print("- mse:{:.4f}".format(model_test_mean_squared_error))
    print("- r2_score:{:.4f}".format(model_test_r2_score))


    print('='*35)
    print('\n')

Linear
Model performnace for traning set
- mae:8574.3313
- mse:155197624.4756
- r2_score:0.9557
-------------------------------------
Model performnace for testing set
- mae:16321.1618
- mse:570300820.0467
- r2_score:0.7353
===================================


Lasso
Model performnace for traning set
- mae:8698.7507
- mse:155859813.8812
- r2_score:0.9555
-------------------------------------
Model performnace for testing set
- mae:16677.4186
- mse:1106160313.4403
- r2_score:0.4866
===================================


Ridge
Model performnace for traning set
- mae:11524.9832
- mse:279002610.2074
- r2_score:0.9203
-------------------------------------
Model performnace for testing set
- mae:15123.9611
- mse:479190876.7862
- r2_score:0.7776
===================================


Decision Tree
Model performnace for traning set
- mae:293.9635
- mse:2745845.2836
- r2_score:0.9992
-------------------------------------
Model performnace for testing set
- mae:17324.7594
- mse:574608912.1880
- r2_score:0.7333
===================================

  File "d:\DS\practice\venv\Lib\site-packages\joblib\externals\loky\backend\context.py", line 247, in _count_physical_cores
    cpu_count_physical = _count_physical_cores_win32()
  File "d:\DS\practice\venv\Lib\site-packages\joblib\externals\loky\backend\context.py", line 299, in _count_physical_cores_win32
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\Python313\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\subprocess.py", line 1551, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^

KNN
Model performnace for traning set
- mae:11998.5889
- mse:512861975.5853
- r2_score:0.8535
-------------------------------------
Model performnace for testing set
- mae:14649.6030
- mse:441597236.8250
- r2_score:0.7950
===================================


Gradient Boost
Model performnace for traning set
- mae:11587.4706
- mse:214922692.5960
- r2_score:0.9386
-------------------------------------
Model performnace for testing set
- mae:14690.1318
- mse:404214038.1605
- r2_score:0.8124
===================================


AdaBoost
Model performnace for traning set
- mae:31276.5382
- mse:1247482340.3790
- r2_score:0.6437
-------------------------------------
Model performnace for testing set
- mae:32472.7362
- mse:1423791448.9290
- r2_score:0.3391
===================================


Random Forest
Model performnace for traning set
- mae:5397.5515
- mse:103927031.5455
- r2_score:0.9703
-------------------------------------
Model performnace for testing set
- mae:15072.9322
- mse:462219349.6219
- r2_score:0.7855
===================================


XGB
Model performnace for traning set
- mae:6542.4873
- mse:70820872.0000
- r2_score:0.9798
-------------------------------------
Model performnace for testing set
- mae:13958.9326
- mse:368073088.0000
- r2_score:0.8292
===================================

In [43]:
trained_models = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print(name)

    trained_models[name] = model   # store fitted model

Linear
Lasso
Ridge
Decision Tree
KNN
Gradient Boost
AdaBoost
Random Forest
XGB

In [44]:
# Gradient_params={
#     "n_estimators":[100,200,500,1000],
#     "learning_rate":[0.05,0.01,0.1,0.2],
#     "max_depth":[1,2,4,5,8,10],
#     "min_samples_leaf":[1,3,5],
#     "min_samples_split":[1,3,5]
    
    
# }
# XGB_params={
#     "n_estimators":[100,200,500,1000],
#     "learning_rate":[0.05,0.01,0.1,0.2],
#     "max_depth":[1,2,4,5,8,10],
#     "min_child_weight":[1,3,5]
# }

In [45]:
# randomcv_model=[
#     ("Gradient_Boosting_Regressor",GradientBoostingRegressor(),Gradient_params),
#     ("XGBRegressor",XGBRegressor(),XGB_params)
# ]

In [46]:
# from sklearn.model_selection import RandomizedSearchCV
# model_param={}
# for name,model,params in randomcv_model:
#     random=RandomizedSearchCV(
#         estimator=model,
#         param_distributions=params,
#         cv=5,
#         scoring='accuracy',
#         n_jobs=-1,
#         n_iter=100
#     )

#     random.fit(X_train,y_train)
#     model_param[name]=random.best_params_
# for model_name in model_param:
#     print(f"-----------------------BEST Parameter{model_name}-----------------------------")
#     print(model_param[model_name])

In [47]:
# models={
#     "Graident Boost":GradientBoostingRegressor(n_estimators= 1000, min_samples_split= 3, min_samples_leaf= 5, max_depth= 8, learning_rate= 0.01),
#     "XGBOOST":XGBRegressor( n_estimators= 1000, min_child_weight= 2, max_depth= 10, learning_rate= 0.1)
# }

In [48]:
# for i in range(len(list(models))):
#     model=list(models.values())[i]
#     model.fit(X_train,y_train)
#     # y_train_pred=(model.predict_proba(X_train)[:,1]>=0.5).astype(int)
#     # y_test_pred=(model.predict_proba(X_test)[:,1]>=0.5).astype(int)
#     y_train_pred=model.predict(X_train)
#     y_test_pred=model.predict(X_test)
    
#     model_train_mae=mean_absolute_error(y_train,y_train_pred)
#     model_train_mean_squared_error=mean_squared_error(y_train,y_train_pred)
#     model_train_r2_score=r2_score(y_train,y_train_pred)
  
    
    
#     model_test_mae=mean_absolute_error(y_test,y_test_pred)
#     model_test_mean_squared_error=mean_squared_error(y_test,y_test_pred)
#     model_test_r2_score=r2_score(y_test,y_test_pred)

    
#     print(list(models.keys())[i])
    
#     print('Model performnace for traning set')
#     print("- mae:{:.4f}".format(model_train_mae))
#     print("- mse:{:.4f}".format(model_train_mean_squared_error))
#     print("- r2_score:{:.4f}".format(model_train_r2_score))

    
#     print("------------------------------------- ")
    
#     print('Model performnace for testing set')
    
#     print("- mae:{:.4f}".format(model_test_mae))
#     print("- mse:{:.4f}".format(model_test_mean_squared_error))
#     print("- r2_score:{:.4f}".format(model_test_r2_score))


#     print('='*35)
#     print('\n')

In [61]:
# import pickle
# pickle.dump(numeric_transformation,open('scaler.pkl','wb'))
# pickle.dump(trained_models['XGB'],open('XGBOOST.pkl','wb'))
# import pickle

# pickle.dump(preprocesser, open("preprocessor.pkl", "wb"))
# pickle.dump(trained_models['XGB'], open("XGBOOST.pkl", "wb"))
X_train = preprocesser.fit_transform(X_train)
X_test = preprocesser.transform(X_test)

model = XGBRegressor()
model.fit(X_train, y_train)

import pickle
pickle.dump(preprocesser, open("models/preprocessor.pkl", "wb"))
pickle.dump(model, open("models/XGBOOST.pkl", "wb"))

ValueError: Specifying the columns using strings is only supported for dataframes.

In [58]:
import sklearn
print(sklearn.__version__)
import xgboost
print(xgboost.__version__)

1.8.0
3.1.3

In [59]:
!pip show scikit-learn
!pip show pandas
!pip show xgboost

Name: scikit-learn
Version: 1.8.0
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License-Expression: BSD-3-Clause
Location: D:\DS\practice\venv\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by:
Name: pandas
Version: 3.0.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: D:\DS\practice\venv\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by: catboost, seaborn, statsmodels
Name: xgboost
Version: 3.1.3
Summary: XGBoost Python Package
Home-page:
Author:
Author-email: Hyunsu Cho <chohyu01@cs.washington.edu>, Jiaming Yuan <jm.yuan@outlook.com>
License: Apache-2.0
Location: D:\DS\practice\venv\Lib\site-packages
Requires: numpy, scipy
Required-by:

In [60]:
!pip install flask

Collecting flask
  Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
Collecting blinker>=1.9.0 (from flask)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in d:\ds\practice\venv\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in d:\ds\practice\venv\lib\site-packages (from flask) (3.0.3)
Collecting werkzeug>=3.1.0 (from flask)
  Downloading werkzeug-3.1.5-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: colorama in d:\ds\practice\venv\lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Downloading flask-3.1.2-py3-none-any.whl (103 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading werkzeug-3.1.5-py3-none-any.whl (225 kB)
Installing collected packages: werkzeug, itsdangerous, click, blinker, flask
Successfully installed blinker-1.9.0 click-8.3.1 flask-3.1.2 itsdangerous-2.2.0 werkzeug-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

ValueError: Specifying the columns using strings is only supported for dataframes.